/** User-facing errors use this prefix; renderer maps to RU/EN via i18n. */
export const RUNTIME_PREFIX = "WIREPN_RUNTIME:" as const;

export const RuntimeErrorCode = {
  NO_PROFILE_SELECTED: `${RUNTIME_PREFIX}NO_PROFILE_SELECTED`,
  MISSING_WIREGUARD_GO: `${RUNTIME_PREFIX}MISSING_WIREGUARD_GO`,
  MISSING_WINTUN: `${RUNTIME_PREFIX}MISSING_WINTUN`,
  WINTUN_ADMIN: `${RUNTIME_PREFIX}WINTUN_ADMIN`,
  UAPI_PIPE_OWNER: `${RUNTIME_PREFIX}UAPI_PIPE_OWNER`,
  WG_GO_EARLY_EXIT: `${RUNTIME_PREFIX}WG_GO_EARLY_EXIT`,
  UAPI_PIPE_NOT_READY: `${RUNTIME_PREFIX}UAPI_PIPE_NOT_READY`,
  UAPI_SET_TIMEOUT: `${RUNTIME_PREFIX}UAPI_SET_TIMEOUT`,
  UAPI_SET_FAILED: `${RUNTIME_PREFIX}UAPI_SET_FAILED`,
  UAPI_CLOSED_NO_ERRNO: `${RUNTIME_PREFIX}UAPI_CLOSED_NO_ERRNO`,
  UAPI_GET_TIMEOUT: `${RUNTIME_PREFIX}UAPI_GET_TIMEOUT`,
  TUNNEL_ROUTE_DENIED: `${RUNTIME_PREFIX}TUNNEL_ROUTE_DENIED`,
  TUNNEL_ROUTE_DUPLICATE: `${RUNTIME_PREFIX}TUNNEL_ROUTE_DUPLICATE`,
  TUNNEL_ADAPTER_NOT_FOUND: `${RUNTIME_PREFIX}TUNNEL_ADAPTER_NOT_FOUND`,
  TUNNEL_POWERSHELL_FAILED: `${RUNTIME_PREFIX}TUNNEL_POWERSHELL_FAILED`,
  PROFILE_NOT_FOUND: `${RUNTIME_PREFIX}PROFILE_NOT_FOUND`,
  WG_PROCESS_EXITED: `${RUNTIME_PREFIX}WG_PROCESS_EXITED`
} as const;

export function runtimeError(code: string, detail?: string): Error {
  return detail !== undefined && detail !== "" ? new Error(`${code}\n${detail}`) : new Error(code);
}
